name: servicios

description: "App de servicios para la Universidad de San Buenaventura."
publish_to: 'none'  # Eliminar esta línea si deseas publicar en pub.dev

version: 1.0.2+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.1
  flutter_datetime_picker: ^1.5.1
  datetime_picker_formfield: ^2.0.1
  flutter_launcher_icons: "^0.13.1"
  flutter_bloc: ^8.1.5
  dio: ^5.4.2+1
  intl: ^0.19.0
  http: ^1.2.1
  http_parser: ^4.0.2
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.6
  mask_text_input_formatter: ^2.9.0

  # Agregar iconos de Cupertino para estilo iOS
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/   # Asegúrate de que esta carpeta contenga tus imágenes
