name: servicios

description: "App de servicios para la Universidad de San Buenaventura."
publish_to: 'none'  # Eliminar esta línea si deseas publicar en pub.dev

version: 1.0.2+1

environment:
  sdk: '>=3.2.2 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter

  # Paquetes principales
  table_calendar: ^3.2.0
  flutter_datetime_picker: ^1.5.1
  flutter_launcher_icons: ^0.14.3
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  intl: ^0.20.2
  http: ^1.3.0
  http_parser: 4.0.2
  file_picker: ^8.0.0
  url_launcher: ^6.3.1
  mask_text_input_formatter: ^2.9.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Verifica si usas lints para un análisis de código más eficiente

flutter:
  uses-material-design: true

  assets:
    - assets/images/
